name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: codeacademy  # Name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # Path to your app's source code
  DOTNET_VERSION: '8'             # .NET version, replace if necessary

on:
  push:
    branches: [ "master" ]  # Adjust branch if needed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Azure CLI login
        run: |
          echo "${{ secrets.AZURE_CLIENT_ID }}" > client_id
          echo "${{ secrets.AZURE_CLIENT_SECRET }}" > client_secret
          echo "${{ secrets.AZURE_TENANT_ID }}" > tenant_id
          az login --service-principal -u $(cat client_id) -p $(cat client_secret) --tenant $(cat tenant_id)
          rm client_id client_secret tenant_id

      - name: Verify Azure Web App exists
        run: |
          az webapp show --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group MyResourceGroup

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
