name: Build and Deploy ASP.Net Core App to Azure Web App

env:
  AZURE_WEBAPP_NAME: codeacademy  # Change this to your Azure Web App name
  AZURE_RESOURCE_GROUP: MyResourceGroup  # Replace with your actual resource group name
  DOTNET_VERSION: '8'

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore AspFinal/AspFinal.csproj

      - name: Build project
        run: dotnet build AspFinal/AspFinal.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish AspFinal/AspFinal.csproj -c Release -o published-app

      - name: Zip the published app
        run: zip -r app.zip published-app

      - name: Deploy to Azure Web App
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

          az webapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --src app.zip
